name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore Dependencies
      run: dotnet restore
      working-directory: ./project

    - name: Build Solution
      run: dotnet build --configuration Release --no-restore
      working-directory: ./project

    - name: Test with the dotnet CLI
      run: dotnet test
      working-directory: ./project

    - name: Restore Dependencies (NUnit Tests)
      run: dotnet restore
      working-directory: ./assignment_3.Tests

    - name: Build Solution (NUnit Tests)
      run: dotnet build --configuration Release --no-restore
      working-directory: ./assignment_3.Tests

    - name: Test with the dotnet CLI (NUnit Tests)
      run: dotnet test
      working-directory: ./assignment_3.Tests
